print()
print("welcome to the debate game")
print()
print("topic is: spiderman vs ironman, which is better")
print()
s1 = input("why is spiderman better:")
print()
print(s1)
print()
i1 = input("why is ironman better:")
print()
print(i1)
print()
s2 = input("why is spiderman better:")
print()
print(s2)
print()
i2 = input("why is ironman better:")
print()
print(i2)
print()
s3 = input("spider man's final reason, make it count:")
print()
print(s3)
print()
i3 = input("ironman's final reason, make it count:")
print()
print(i3)
print()
judge = input("who wins this debate|ironman or|spiderman:")
print()
if judge == "spiderman":
    print("spiderman is better")
elif judge == "ironman":
    print("ironman is better")
else:
    print("judge didn't judge for some reason.")